[Smart Columbus Operating System link](https://ckan.smartcolumbusos.com/dataset/census-block-groups-20101)

Last Updated: May 9, 2018, 7:23 PM (UTC-04:00)

Description: 2010 Census Blockgroups and selected demographic data for 12 county Central Ohio region for years 2000 and 2010.
---
[Homepage URL](http://public-morpc.opendata.arcgis.com/datasets/1de4b1b227ea410a86d039affbe50e32_0)

Fields:
- OBJECTID ( type: esriFieldTypeOID , alias: OBJECTID )
- FIPSSTCO ( type: esriFieldTypeString , alias: FIPSSTCO , length: 10 )
- GEOID ( type: esriFieldTypeString , alias: GEOID , length: 254 )
- COUNTY ( type: esriFieldTypeString , alias: County , length: 3 )
- TOTPOP10 ( type: esriFieldTypeDouble , alias: 2010 Total Population )
- WHITE10 ( type: esriFieldTypeDouble , alias: 2010 White Population )
- AFAM10 ( type: esriFieldTypeDouble , alias: 2010 African American Population )
- ASIAN10 ( type: esriFieldTypeDouble , alias: 2010 Asian Population )
- OTHER10 ( type: esriFieldTypeDouble , alias: 2010 Other Races Population )
- HISPANIC10 ( type: esriFieldTypeDouble , alias: 2010 Hispanic Population )
- TOTHU10 ( type: esriFieldTypeDouble , alias: 2010 Total Households )
- OCCHU10 ( type: esriFieldTypeDouble , alias: 2010 Occupied Households )
- VACHU10 ( type: esriFieldTypeDouble , alias: 2010 Vacant Households )
- Sum00_TotPOP ( type: esriFieldTypeDouble , alias: 2000 Total Population )
- Sum00_White ( type: esriFieldTypeDouble , alias: 2000 White Population )
- Sum00_Africa ( type: esriFieldTypeDouble , alias: 2000 African American Population )
- Sum00_Asian ( type: esriFieldTypeDouble , alias: 2000 Asian Population )
- Sum00_other ( type: esriFieldTypeDouble , alias: 2000 Other Races Population )
- Sum00_TotHU ( type: esriFieldTypeDouble , alias: 2000 Total Housing Units )
- Sum00_OccHU ( type: esriFieldTypeDouble , alias: 2000 Occupied Housing Units )
- Sum00_VacHU ( type: esriFieldTypeDouble , alias: 2000 Vacant Housing Units )
- Sum00_HISP ( type: esriFieldTypeDouble , alias: 2000 Hispanic Population )
- Shape ( type: esriFieldTypeGeometry , alias: Shape )
- GlobalID ( type: esriFieldTypeGlobalID , alias: GlobalID , length: 38 )
- Shape_Length ( type: esriFieldTypeDouble , alias: Shape_Length )
- Shape_Area ( type: esriFieldTypeDouble , alias: Shape_Area )
